---
output: html_document
editor_options: 
  chunk_output_type: console
---


```{R}
library(readxl)
library(readr)

```

```{R}



# point towards directory
# point towards workbook THIS WILL CHANGE SOON!
drive <- "~/Desktop/"
setwd(drive)
workbook <- "~/Desktop/workbooks/2018 AK Energy Statistics early release.xlsx"

# Read sheets and use for filenames
sheets <- excel_sheets(workbook)
filenames <- paste0(sheets, ".csv")

# read_excel only reads a single sheet, so lapply over each sheet name
dat <- lapply(sheets, read_excel, path = workbook)

# point towards location to save raw CSV files (sheets)
save_raw <- "~/repos/ak-energy-statistics-2011_2021/2018/raw/"
setwd(save_raw)

# I dream of idempotency..
# Save each data frame with different filename using write_csv
# lapply(seq_along(dat), function(i) write_csv(dat[[i]], filenames[i]))




```


```{R}
setwd(save_raw)

i <- NULL
df <- NULL

for(i in filenames){
  assign(gsub(".csv", "", paste(i)), read.csv(paste(i)))
}






```


set target for cleaned files
**VERY IMPORTANT**
```{R}
save_staging <- "~/repos/ak-energy-statistics-2011_2021/2018/staging/"
setwd(save_staging)




```





# TEMPLATE! COPY, DONT CHANGE
## table   
### 
```{R}
# save title
title_ <- `Table `[1,1]
print(title_)

# save column names
# watch out! different than others
colnames(`Table `) <- `Table `[2, ]

# delete first row (title), and third row (column names)
`Table ` <- `Table `[-c(1,2), ]

```


## table 2.4a
"Net Generation, Fuel Type, Emissions, Efficiency by Certified Utilities, 2018"

"Fuel Types: AB=Agricultural By-Products, DFO=Distillate Fuel Oil, JF=Jet Fuel, NG=Natural Gas, OTH=Other, RFO=Residual Fuel Oil, SUB=Sub-bituminous Coal, WAT=Water at a Conventional Hydroelectric Turbine, WC=Waste Coal, WDS=Wood Solids, WND=Wind, WO=Waste/Other Oil"

"Prime Movers: CA=Combined Cycle, steam part, CT=Combined Cycle=turbine part, GT=Gas Turbine, HY=Hydroelectric Turbine, IC=Internal Combustion Engine, ST=Steam Turbine, WT=Wind Turbine"

```{R}
# save title
title_2.4a <- `Table 2.4a`[1,1]
print(title_2.4a)

# metadata riders, print in comments above this chunk, then delete for now
print(`Table 2.4a`[2,1])
print(`Table 2.4a`[3,1])

# save fourth row as column names
# watch out! different than others
colnames(`Table 2.4a`) <- `Table 2.4a`[4, ]

# delete extra rows
`Table 2.4a` <- `Table 2.4a`[-c(1:4), ]


setwd(save_staging)
write.csv(`Table 2.4a`, file = "./table_2.4a.csv", row.names = FALSE)

```



# Tables 2.5x below

## table 2.5a
### "Table 2.5a Revenue, Sales and Customers by Customer Type by Operators/Utilities ($000, MWh, Accounts), 2021"
```{R}
# extract title, use for idempotency below
title_2.5a <- `Table 2.5a`[1,1]
print(title_2.5a)

# use table title as qualifyer for cleaning expression
if(`Table 2.5a`[1,1] == "Revenue, Sales and Customers by Customer Type by Certified Utilities ($000, MWh, Accounts), 2018") {
  
  # save second row as column names
  colnames(`Table 2.5a`) <- `Table 2.5a`[2, ]
  
  # delete first row (title), second row (blank), and third row (column names)
  `Table 2.5a` <- `Table 2.5a`[-c(1:2), ]

}

setwd(save_staging)
write.csv(`Table 2.5a`, file = "./table_2.5a.csv", row.names = FALSE)

```

## table 2.5b
### "Table 2.5b  Average Annual Energy Use and Rates by Customer Type by Operators/Utilities, (kWh/Customer, $/Customer, $/kWh), 2021"
```{R}
# save title, use to prevent repeat of cleaning expression
title_2.5b <- `Table 2.5b`[1,1]
print(title_2.5b)

if(`Table 2.5b`[1,1] == "Revenue, Sales and Customers by Customer Type by Certified Utilities ($000, MWh, Accounts), 2018"){
  # save second row as column names
  colnames(`Table 2.5b`) <- `Table 2.5b`[2, ]
  
  # delete first row (title), second row (blank) and third row (column names)
  `Table 2.5b` <- `Table 2.5b`[-c(1:2), ]

}

setwd(save_staging)
write.csv(`Table 2.5b`, file = "./table_2.5b.csv", row.names = FALSE)

```


## table 2.5c
### "Table 2.5c  Average Residential Rates and PCE Payments ($/kWh), 2021"
```{R}
# save title
title_2.5c <- `Table 2.5c`[1,1]
print(title_2.5c)

if(`Table 2.5c`[1,1] == "Certified Utilities Revenue, Sales and Customers by Customer Type, 2018"){
  # save third row as column names
  colnames(`Table 2.5c`) <- `Table 2.5c`[2, ]
  
  # delete first row (title), second row (blank), and third row (column names)
  `Table 2.5c` <- `Table 2.5c`[-c(1:2), ]
}

setwd(save_staging)
write.csv(`Table 2.5c`, file = "./table_2.5c.csv", row.names = FALSE)
  
```

