---
title: "revenue"
output: html_document
date: "2024-01-29"
editor_options: 
  chunk_output_type: console
---

### Build a library
```{R}
options(scipen=999)

library(dplyr)
library(tidyr)
library(ggplot2)
library(lubridate)
library(forcats)
library(stringr)

library(readxl)
library(readr)

library(see)  # slices violin plots in half
library(ggridges) # mountains beyond mountains
library(ggrepel) # labels on ends of lines
library(ggdist) # raincloud plots
library(ggrain) # other raincloud package

```

### Set working directory
```{R}
repo <- "~/repos/ak-energy-statistics-2011_2021/"
setwd(repo)

```

### Load data
```{R}

price <- read_csv("./trends/raw/prices_pce_inflation.csv")

```

# exploratory
# price vs population
# do larger communities have cheaper rates? (sort of)
```{R}
# price %>%
#   # filter(Year == 2018) %>%
#   filter(`Total Customers` > 0) %>%
# ggplot(aes(x =`Total Customers`, 
#            y = `Other Price kWh (2021 dollars)`)) + 
#            # size = `Residential Customers`,
#            # color = `ACEP Energy Region`)) +
#   geom_point() +
#   geom_smooth() +
#   # facet_grid(rows = vars(`ACEP Energy Region`)) +
#   theme_classic() +
#   theme(legend.position = "none",
#         plot.title = element_text(size=20, hjust = 0.5),
#         plot.subtitle = element_text(size=14, hjust = 0.5),
#         plot.caption = element_text(size = 8)) +
#   labs(title = "Price v Population, All Regions",
#        subtitle = "Do larger communities pay lower rates?") +
#   
#   
#   
#   # ylim(0,250) +
#   xlim(0,8000)
# 
# 
# # linear reg
# model <- lm(`Total Customers` ~ `Residential Price kWh (2021 dollars)`, data = price)
# summary(model)
# 
# 
# 
# test <- price %>%
#   filter(`Total Customers` > 0) %>%
#   filter(`Total Customers` < 50) %>%
#   filter(Year == 2021)
# 
# 
# tmp <- price %>%
#   filter(`ACEP Energy Region` == "Rural Remote")
# 
#   length(unique(tmp$`AEA Sales Reporting ID`))



```



## pivot longer to get Residential, Commercial, Other
```{R}
p_price <- price %>%
             rename(c("Residential" = "Residential Price kWh (2021 dollars)",
                      "Commercial" = "Commercial Price kWh (2021 dollars)",
                      "Other" = "Other Price kWh (2021 dollars)")) %>%
             pivot_longer( 
             cols = c("Residential",
                      "Commercial",
                      "Other"), 
             names_to ="Sector", 
             values_to = "Price")

long_price <- p_price %>%
  mutate(Customers = NA) %>%
  mutate(Customers = ifelse(Sector == "Residential", `Residential Customers`, Customers)) %>%
  mutate(Customers = ifelse(Sector == "Commercial", `Commercial Customers`, Customers)) %>%
  mutate(Customers = ifelse(Sector == "Other", `Other Customers`, Customers)) %>%
  mutate(Customers = round(Customers, 0)) %>%
  
  select("Year",
         "Reporting Name",
         "ACEP Energy Region",
         "Sector",
         "Price",
         "Customers",
         "Total Customers")



```



# calculate weighted averages
```{R}
weighted <- long_price %>%
  drop_na() %>%
  group_by(`ACEP Energy Region`, Sector, Year) %>%
  summarize(avg_price = mean(Price, na.rm=T),
            weighted_price = weighted.mean(Price, `Customers`, na.rm=T))

```


explore rural remote customer fiasco
We're noticing huge swings in number of customers in each sector
Looks like there was a reclassification event?
```{R}
# cust <- long_price %>%
#   drop_na() %>%
#   group_by(`ACEP Energy Region`, Year, Sector) %>%
#   summarize(sector_customers = sum(`Customers`)) 
# 
# plot_region <- "Coastal"
# 
# cust %>% 
#   filter(`ACEP Energy Region` == plot_region) %>%
#   ggplot() +
#   geom_line(aes(y=sector_customers, x=Year, color=Sector)) +
#   labs(title = paste(plot_region, "Region", "Customers by Sector", sep=" "),
#        y = "Customers") +
#   scale_y_continuous(breaks=seq(0,200000,5000))



```




# Line graph of price by sector by region
# POPULATION-WEIGHTED
# 2011-2019
```{R}

viz <- NULL

plot_region <- "Coastal"

# with weighted data
viz <- weighted %>%
  filter(`ACEP Energy Region` == paste(plot_region)) %>%
  filter(Year <= 2019)

viz %>%  
  mutate(label = if_else(Year == max(Year), as.character(Sector), NA_character_)) %>%
  ggplot( aes(y=weighted_price, x=Year, color = Sector)) +
  geom_line(linewidth=1.5) +
  geom_label_repel(aes(label = label,),
                  nudge_x = 1,
                  nudge_y = 1,
                  na.rm = TRUE) +
  theme_classic() +
  
  scale_color_manual(values = c("#e29617", "#fad900", "#0084c1")) + #Commercial, Other, Residential
  theme(legend.position = "none",
        plot.title = element_text(size=20, hjust = 0.5),
        plot.subtitle = element_text(size=18, hjust = 0.5),
        plot.caption = element_text(size = 10)) +
  
  labs(title = "Average Price of Electricity by Sector",
       subtitle = paste(plot_region, " Region", sep = ""),
       caption = "Population-Weighted averages, Inflation-adjusted (2021 dollars), post-PCE subsidy",
       x = "Year",
       y = "Cents/kWh") +

# Coastal
   # ylim(c(0,90)) +
# Railbelt
   # ylim(c(0,85)) +
# Rural Remote
   ylim(c(0,45)) +


   scale_x_continuous(breaks=seq(2011,2021,2))


# prep for write
setwd(repo)
setwd("./trends/visuals/price_sector")

# write the source data
viz_data_filepath <- gsub(" ", "_", (paste("./price_sector_", str_to_lower(plot_region), ".csv", sep = "")))
write_csv(viz, file = viz_data_filepath)

# write the visual in EPS
viz_plot_filename <- gsub(" ", "_", (paste("price_sector_", str_to_lower(plot_region), ".eps", sep = "")))
ggsave(filename = viz_plot_filename, device = "eps", )

setwd(repo)

```



## half violin of yearly data, grouped by region
# straight data points, no weighting
# 2011-2019
```{R}


# plot
viz <- long_price %>%
  filter(Sector == "Residential") %>% 
  filter(Price > 0) %>%
  filter(Year <= 2019) %>%
  left_join(weighted, join_by(Year, Sector, `ACEP Energy Region`))
  
viz %>%
  ggplot() +
  
    geom_violinhalf(aes(x=`ACEP Energy Region`, 
                        y=Price, 
                        fill=`ACEP Energy Region`),
                    position = position_nudge(x=.1, y=0)) +
  
    geom_jitter(aes(x=`ACEP Energy Region`, 
                        y=Price, 
                        fill=`ACEP Energy Region`,
                        size = `Total Customers`),
                color="black", 
                alpha=0.5, 
                width = .1,
                height = 0
                # position = position_nudge(x=-0.1, y=0)
                ) +
  
    geom_boxplot(aes(x=`ACEP Energy Region`,
                     y=weighted_price,
                     fill=`ACEP Energy Region`),
                 width=0.4,
                 alpha=0.7,
                 position = position_nudge(x=0.3, y=0)) +
  
    scale_fill_manual(values = c("#98BAD6", "#A4CD9A", "#E3918F")) +
    scale_color_manual(values = c("#98BAD6", "#A4CD9A", "#E3918F")) +

    theme_classic() +
    theme(legend.position = "none",
          plot.title = element_text(size=20, hjust = 0.5),
          plot.subtitle = element_text(size=14, hjust = 0.5),
          plot.caption = element_text(size = 8)) +
  
    labs(title = "Price of Residential Electricity, 2011-2019",
         subtitle = "Population-weighted averages",
         caption = "Inflation-adjusted to 2021 dollars, post PCE Subsidy",
         x = "Region",
         y = "Cents/kWh") +

    ylim(c(0,65)) +
    coord_flip() 




```



# Line graph of three regions, all sectors
# POP WEIGHTED
```{R}

viz <- weighted %>%
  group_by(`ACEP Energy Region`, Year) %>%
  filter(Year <= 2019) %>%
  summarize(weighted_price = mean(weighted_price))


# commented code below add labels at ends of lines
viz %>%
  # mutate(label = if_else(Year == max(Year), as.character(`ACEP Energy Region`), NA_character_)) %>%
  ggplot( aes(y=weighted_price, x=Year, color = `ACEP Energy Region`)) +
  geom_line(linewidth=1.5) +
  # geom_label_repel(aes(label = label,),
  #                 nudge_x = 1,
  #                 nudge_y = 1,
  #                 na.rm = TRUE) +
  theme_bw() +

  scale_color_manual(values = c("#98BAD6", "#A4CD9A", "#E3918F")) +
  theme(legend.position = "right",
        legend.title = element_blank(),
        legend.text = element_text(size=12),
        # plot.title = element_text(size=20, hjust = 0.5),
        # plot.subtitle = element_text(size=14, hjust = 0.5),
        axis.text = element_text(size=12),
        axis.title = element_text(size=14),
        plot.caption = element_text(size = 10)) +

  labs(title = element_blank(),
       subtitle = element_blank(),
       caption = "Population-weighted averages, inflation-adjusted to 2021 dollars, post PCE Subsidy",
       x = element_blank(),
       y = "Cents per kWh") +

   scale_y_continuous(breaks=seq(0,60,10), limits=c(0,60), expand = expansion(mult = 0)) +
   scale_x_continuous(breaks=seq(2011,2019,1), limits=c(2011,2019), expand = expansion(mult = 0)) 



# write the source data
viz_data_filepath <- "./trends/visuals/price_region/price_region.csv"
write_csv(viz, file = viz_data_filepath)

# write the visual in EPS
viz_plot_filename <- "./trends/visuals/price_region/price_region.eps"
ggsave(filename = viz_plot_filename, 
       device = "eps", 
       height = 4,
       width = 6.5,
       units = "in")



```





# DEPRECATED: cut communities below 300
```{R}
# # cut communities below threshold population
# no_small <- price %>%
#              filter(`Total Customers` > 300) %>%
#              rename(c("Residential" = "Residential Price kWh (2021 dollars)",
#                       "Commercial" = "Commercial Price kWh (2021 dollars)",
#                       "Other" = "Other Price kWh (2021 dollars)")) %>%
#              pivot_longer( 
#              cols = c("Residential",
#                       "Commercial",
#                       "Other"), 
#              names_to ="Sector", 
#              values_to = "Price")
# 
# long_no_small <- no_small %>%
#   mutate(Customers = NA) %>%
#   mutate(Customers = ifelse(Sector == "Residential", `Residential Customers`, Customers)) %>%
#   mutate(Customers = ifelse(Sector == "Commercial", `Commercial Customers`, Customers)) %>%
#   mutate(Customers = ifelse(Sector == "Other", `Other Customers`, Customers)) %>%
#   mutate(Customers = round(Customers, 0)) %>%
#   
#   select("Year",
#          "Reporting Name",
#          "ACEP Energy Region",
#          "Sector",
#          "Price",
#          "Customers")
# 
# # calculate averages
# avg_no_small <- long_no_small %>%
#   drop_na() %>%
#   group_by(`ACEP Energy Region`, Sector, Year) %>%
#   summarize(avg_price = mean(Price, na.rm=T),
#             weighted_price = mean(Price, na.rm=T))



```



# DEPRECATED
# Line graph of price by sector by region
# MINUS SMALL COMMUNITIES (300 ppl)
```{R}

# # plot
# 
# plot_region <- "Coastal"
# 
# # with small communities cut
# viz <- avg_no_small %>%
#   filter(`ACEP Energy Region` == paste(plot_region))
# 
# viz %>%  
#   mutate(label = if_else(Year == max(Year), as.character(Sector), NA_character_)) %>%
#   ggplot( aes(y=avg_price, x=Year, color = Sector)) +
#   geom_line(linewidth=1.5) +
#   geom_label_repel(aes(label = label,),
#                   nudge_x = 1,
#                   nudge_y = 1,
#                   na.rm = TRUE) +
#   theme_classic() +
#   
#   scale_color_manual(values = c("#848BA7", "#645345", "#8F6A9D")) + #Commercial, Other, Residential
#   theme(legend.position = "none",
#         plot.title = element_text(size=20, hjust = 0.5),
#         plot.subtitle = element_text(size=18, hjust = 0.5),
#         plot.caption = element_text(size = 10)) +
#   
#   labs(title = "MINUS SMALL COMMUNITIES (<300), Price of Electricity, 2011-2021",
#        subtitle = paste(plot_region, " Region",sep = ""),
#        caption = "Comunities < 300 removed, inflation-adjusted (2021 dollars), post-PCE subsidy",
#        x = "Year",
#        y = "Cents/kWh") +
# 
#    ylim(c(0,100)) +
#    scale_x_continuous(breaks=seq(2011,2021,2))


```


# DEPRECATED
## raincloud plot of 2021 data, grouped by region
# straight data points, no weighting
```{R}

# # plot
# no_small %>%
#   filter(Sector == "Residential") %>%
#   mutate(fct_total_customers = as_factor(`Total Customers`)) %>%
#   ggplot( aes(x=`ACEP Energy Region`, 
#               y=Price, 
#               fill=`ACEP Energy Region`,
#               size = `Total Customers`,
#               group = `ACEP Energy Region`)) +
# 
#   
#   geom_rain(alpha = 0.7, rain.side = 'r',
#             violin.args = list(color = "black", alpha = 1),
#             boxplot.args = list(alpha = 1, color = "black", outlier.shape = NA),
#             boxplot.args.pos = list(
#               position = ggpp::position_dodgenudge(x = .1, width = 0.1), width = 0.1
#             )) +
#   
#   
#     scale_fill_manual(values = c("#98BAD6", "#A4CD9A", "#E3918F")) +
#     theme_classic() +
#     theme(legend.position = "none",
#           plot.title = element_text(size=20, hjust = 0.5),
#           plot.subtitle = element_text(size=14, hjust = 0.5),
#           plot.caption = element_text(size = 8)) +
#   
#     labs(title = "Price of Electricity, Residential, 2011-2021",
#          subtitle = "Inflation-adjusted to 2021 dollars, post PCE Subsidy",
#          caption = "Inflation-adjustment calculated using BLS Cost Price Index, AK Urban",
#          x = "Region",
#          y = "unitless?") +
#   
#     coord_flip() 
# 
#     ylim(c(0,75))
#     
# 
#     #E3918F Rural Remote
#     #98BAD6 Coastal
#     #A4CD9A Railbelt
#     #F1BF42 State

```



# DEPRECATED
# Line graph of three regions, all sectors
# NOT WEIGHTED
```{R}
# 
# viz <- long_price %>%
#   group_by(`ACEP Energy Region`, Year) %>%
#   summarize(avg_price = mean(Price, na.rm = T))
# 
# 
# 
# viz %>%  
#   mutate(label = if_else(Year == max(Year), as.character(`ACEP Energy Region`), NA_character_)) %>%
#   ggplot( aes(y=avg_price, x=Year, color = `ACEP Energy Region`)) +
#   geom_line(linewidth=1.5) +
#   geom_label_repel(aes(label = label,),
#                   nudge_x = 1,
#                   nudge_y = 1,
#                   na.rm = TRUE) +
#   theme_classic() +
#   
#   scale_color_manual(values = c("#98BAD6", "#A4CD9A", "#E3918F")) +
#   theme(legend.position = "none",
#         plot.title = element_text(size=20, hjust = 0.5),
#         plot.subtitle = element_text(size=14, hjust = 0.5),
#         plot.caption = element_text(size = 8)) +
#   
#   labs(title = "Average Price of Electricity, 2011-2021",
#        subtitle = "Inflation-adjusted to 2021 dollars, post PCE Subsidy",
#        caption = "Inflation-adjustment calculated using BLS Cost Price Index, AK Urban",
#        x = "Year",
#        y = "Cents per kWh") +
# 
#    ylim(0,75) +
#    scale_x_continuous(breaks=seq(2011,2021,2)) 




```


# Line graph of three regions, all sectors
# Small communities removed
```{R}

# viz <- avg_no_small %>%
#   group_by(`ACEP Energy Region`, Year) %>%
#   summarize(avg_price = mean(avg_price))
# 
# 
# 
# viz %>%  
#   mutate(label = if_else(Year == max(Year), as.character(`ACEP Energy Region`), NA_character_)) %>%
#   ggplot( aes(y=avg_price, x=Year, color = `ACEP Energy Region`)) +
#   geom_line(linewidth=1.5) +
#   geom_label_repel(aes(label = label,),
#                   nudge_x = 1,
#                   nudge_y = 1,
#                   na.rm = TRUE) +
#   theme_classic() +
#   
#   scale_color_manual(values = c("#98BAD6", "#A4CD9A", "#E3918F")) +
#   theme(legend.position = "none",
#         plot.title = element_text(size=20, hjust = 0.5),
#         plot.subtitle = element_text(size=14, hjust = 0.5),
#         plot.caption = element_text(size = 8)) +
#   
#   labs(title = "SMALL COMM REMOVED (below 300 ppl) Average Price of Electricity, 2011-2021",
#        subtitle = "Inflation-adjusted to 2021 dollars, post PCE Subsidy",
#        caption = "Inflation-adjustment calculated using BLS Cost Price Index, AK Urban",
#        x = "Year",
#        y = "Cents per kWh") +
# 
#    ylim(0,70) +
#    scale_x_continuous(breaks=seq(2011,2021,2)) 
# 
# 
# 

```






#NON WEIGHTED
## boxplot of 2021 data, grouped by region
```{R}
# # plot
# price %>%
#   filter(Year == 2011) %>%
#   ggplot( aes(x=`ACEP Energy Region`, 
#               y=`Residential Price kWh (2021 dollars)`, 
#               fill=`ACEP Energy Region`,
#               size=`Residential Customers`)) +
#     # geom_boxplot(outlier.alpha = 0) +
#     geom_violinhalf() +
#     scale_fill_manual(values = c("#98BAD6", "#A4CD9A", "#E3918F")) +
#     geom_jitter(color="black", alpha=0.8, width = 0.1, height = 0) +
#     theme_classic() +
#     theme(legend.position = "none",
#           plot.title = element_text(size=20, hjust = 0.5),
#           plot.subtitle = element_text(size=14, hjust = 0.5),
#           plot.caption = element_text(size = 8)) +
#   
#     labs(title = "Price of Electricity, Residential, 2011",
#          subtitle = "Inflation-adjusted to 2021 dollars, post PCE Subsidy",
#          caption = "Inflation-adjustment calculated using BLS Cost Price Index, AK Urban",
#          x = "Region",
#          y = "Cents/kWh") +
#   
#     coord_flip() +
#     
#     ylim(c(0,50)) 
#     

    #E3918F Rural Remote
    #98BAD6 Coastal
    #A4CD9A Railbelt
    #F1BF42 State

```









# ridges over time
# NONWEIGHTED (distribution)
```{R}
price %>%
  filter(`ACEP Energy Region` == "Coastal") %>%
  mutate(YearFct = fct_rev(as.factor(Year))) %>%
  ggplot( aes(x=`Residential Price kWh (2021 dollars)`, y=YearFct, fill = YearFct)) +
  geom_density_ridges() + 
  theme_classic() +
  theme(legend.position = "none") +
  ggtitle("Price per kWh (2021 dollars), Coastal Residential")



```











# Junkyard below






# DEPRECATED price over time
# boxplots over time by region, facet-wrapped
# too busy!
# ```{R}
# # facet_grid by region by residential/commercial/Other
# p_price %>%
#   filter(`ACEP Energy Region` == "Coastal") %>%
#   mutate(YearFct = as.factor(Year)) %>%
# 
#   # boxplot code
#   ggplot( aes(y=Price, x=YearFct, fill = YearFct)) +
#   geom_boxplot(outlier.alpha = 0) +
#   facet_grid(~Type) +
#   theme_classic() +
# 
#   theme(legend.position = "none",
#         plot.title = element_text(size=20, hjust = 0.5),
#         plot.subtitle = element_text(size=14, hjust = 0.5),
#         plot.caption = element_text(size = 8)) +
#   
#   labs(title = "Price of Electricity, Coastal, 2011-2021",
#        subtitle = "Inflation-adjusted to 2021 dollars, post PCE Subsidy",
#        caption = "Inflation-adjustment calculated using BLS Cost Price Index, AK Urban",
#        x = "Year",
#        y = "Cents per kWh") 
# 
#   ylim(c(0,100))
#   
# 
# ```
# 
# 
# ## dealing with outliers in rural remote
# ```{R}
# data <- res_rev21
# dim(data)
#  
# list_quantiles <- tapply(data$`Residential Revenue kWh`, data$`ACEP energy region`, quantile)
#  
# Q1s <- sapply(1:3, function(i) list_quantiles[[i]][2])
# Q3s <- sapply(1:3, function(i) list_quantiles[[i]][4])
#  
# IQRs <- tapply(data$`Residential Revenue kWh`, data$`ACEP energy region`, IQR)
#  
# Lowers <- Q1s - 1.5*IQRs
# Uppers <- Q3s + 1.5*IQRs
#  
# datas <- split(data, data$`ACEP energy region`)
#  
# data_no_outlier <- NULL
# for (i in 1:3){
# out <- subset(datas[[i]], datas[[i]]$`Residential Revenue kWh` > Lowers[i] & datas[[i]]$`Residential Revenue kWh` < Uppers[i])
# data_no_outlier <- rbind(data_no_outlier, out)
# }
#  
# dim(data_no_outlier)
# 
# 
# 
# ```
# 
# ## colnames comparison
# probably not worth pursuing, just pull common columns and join
# ```{R}
# cols <- data.frame   (col2021 = c(colnames(rev2021)), 
#                       col2020 = c(colnames(rev2020)),
#                       col2019 = c(colnames(rev2019)),
#                       col2018 = c(colnames(rev2018)),
#                       col2017 = c(colnames(rev2017)),
#                       col2016 = c(colnames(rev2016))
#                       )
# ```
# 








